"""

https://mermaid.live/edit#pako:eNp1kcFugzAMhl_Fypm-AIedWLXuVI1Ku-TiJQYikQQFp1NX-u5LYAIJdTf_9uffv-S7UF6TKEXT-2_VYWC4VNJJHuNXG3Do4PNUvX7AOJAyjVF5JPl9oPZksaVFHlHRGVl1i3zD8a-qzU9GVugY0NIGweHwArt-XnnWX0_m4eQdFXA1CAi9R01hWnHYZZp5dLf_-IyT00vMChnP3jhe5GaaTZwPFnszkgb20w5d5YzadBA4oHHGtTNaEz_BYsp3TZ4amTZMFMJSumV0esxdOgApuKOUVZSp1NRg7FkK6R4Jxci-vjklSg6RChGH7FYZTP-zS_PxC2sPsMo

"""



class JpegImage

class FacePatch

class FaceFrame

class DataPoint

class DataSet
